# Generated by Django 4.2 on 2023-05-13 11:20

import autoslug.fields
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirimModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birim', models.CharField(max_length=30)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='birim', unique=True)),
            ],
            options={
                'verbose_name': 'birim',
                'verbose_name_plural': 'birimler',
                'db_table': 'birim',
            },
        ),
        migrations.CreateModel(
            name='DepartmanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departman_adi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Departman',
                'verbose_name_plural': 'Departmanlar',
                'db_table': 'departman',
            },
        ),
        migrations.CreateModel(
            name='GorevliModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorevli_isim_soyisim', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Görevli',
                'verbose_name_plural': 'Görevliler',
                'db_table': 'gorevli',
            },
        ),
        migrations.CreateModel(
            name='IletisimModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('isim_soyisim', models.CharField(max_length=150)),
                ('mesaj', models.TextField()),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'İletişim',
                'db_table': 'iletisim',
            },
        ),
        migrations.CreateModel(
            name='KategoriModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=30)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='isim', unique=True)),
            ],
            options={
                'verbose_name': 'kategori',
                'verbose_name_plural': 'kategoriler',
                'db_table': 'kategori',
            },
        ),
        migrations.CreateModel(
            name='MalzemeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malzeme_adi', models.CharField(max_length=50)),
                ('malzeme_adedi', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Malzeme',
                'verbose_name_plural': 'Malzemeler',
                'db_table': 'malzeme',
            },
        ),
        migrations.CreateModel(
            name='YazilarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='yazi_resimleri')),
                ('baslik', models.CharField(max_length=50)),
                ('icerik', ckeditor.fields.RichTextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='baslik', unique=True)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('düzenlenme_tarihi', models.DateTimeField(auto_now=True)),
                ('kategoriler', models.ManyToManyField(related_name='yazi', to='blog.kategorimodel')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yazilar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yazi',
                'verbose_name_plural': 'Yazilar',
                'db_table': 'Yazi',
            },
        ),
        migrations.CreateModel(
            name='YorumModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('yorum', models.TextField()),
                ('yazan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorum', to=settings.AUTH_USER_MODEL)),
                ('yazi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='blog.yazilarmodel')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'db_table': 'yorum',
            },
        ),
        migrations.CreateModel(
            name='TasimaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=50, null=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('gorevli_kisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorevli_kisi_tasima', to='blog.gorevlimodel')),
            ],
            options={
                'verbose_name': 'Tasima Formu',
                'verbose_name_plural': 'Tasima Formları',
                'db_table': 'tasima',
            },
        ),
        migrations.CreateModel(
            name='SunCalisanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=100, null=True)),
                ('soyisim', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_no', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sifre', models.CharField(max_length=50)),
                ('departman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departman', to='blog.departmanmodel')),
            ],
            options={
                'verbose_name': 'Sun Şirket Çalışanı',
                'verbose_name_plural': 'Sun Şirket Çalışanları',
                'db_table': 'sun_calisan',
            },
        ),
        migrations.CreateModel(
            name='SarfMalzemeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=50, null=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('sarf_malzeme_adedi', models.IntegerField()),
                ('kategori_ismi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategori_ismi', to='blog.kategorimodel')),
                ('sarf_malzeme_adi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sarf_malzeme_ismi', to='blog.malzememodel')),
            ],
            options={
                'verbose_name': 'Sarf Malzeme Formu',
                'verbose_name_plural': 'Sarf Malzeme Formları',
                'db_table': 'sarf_malzeme',
            },
        ),
        migrations.CreateModel(
            name='İdariYoneticiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=100, null=True)),
                ('soyisim', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_no', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sifre', models.CharField(max_length=50)),
                ('calistigi_birim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yonetici_birimi', to='blog.birimmodel')),
            ],
            options={
                'verbose_name': 'İdari Birim Yöneticisi',
                'verbose_name_plural': 'İdari Birim Yöneticisi',
                'db_table': 'idari_yonetici',
            },
        ),
        migrations.CreateModel(
            name='İdariCalisanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=100, null=True)),
                ('soyisim', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_no', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sifre', models.CharField(max_length=50)),
                ('calistigi_birim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idari_calisan_birimi', to='blog.birimmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İdari Birim Çalışanı',
                'verbose_name_plural': 'İdari Birim Çalışanları',
                'db_table': 'idari_birim_calisan',
            },
        ),
        migrations.CreateModel(
            name='HijyenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=50, null=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('gorevli_kisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorevli_kisi_hijyen', to='blog.gorevlimodel')),
            ],
            options={
                'verbose_name': 'Hijyen Formu',
                'verbose_name_plural': 'Hijyen Formları',
                'db_table': 'hijyen',
            },
        ),
    ]
