# Generated by Django 4.2 on 2023-05-15 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='i̇daricalisanmodel',
            name='user',
        ),
    ]
