# Generated by Django 4.1.8 on 2023-05-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_i_daricalisanmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hijyenmodel',
            name='idari_calisan',
            field=models.CharField(choices=[('Pınar Hanım', 'Pınar Hanım'), ('Bahar Hanım', 'Bahar Hanım')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hijyenmodel',
            name='islem_durumu',
            field=models.CharField(choices=[('Onay Bekliyor', 'Onay Bekliyor'), ('Onaylandı', 'Onaylandı'), ('Reddedildi', 'Reddedildi'), ('İşlem Yapılıyor', 'İşlem Yapılıyor')], default='Onay Bekliyor', max_length=50),
        ),
        migrations.AddField(
            model_name='sarfmalzememodel',
            name='idari_calisan',
            field=models.CharField(choices=[('Pınar Hanım', 'Pınar Hanım'), ('Bahar Hanım', 'Bahar Hanım')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sarfmalzememodel',
            name='islem_durumu',
            field=models.CharField(choices=[('Onay Bekliyor', 'Onay Bekliyor'), ('Onaylandı', 'Onaylandı'), ('Reddedildi', 'Reddedildi'), ('İşlem Yapılıyor', 'İşlem Yapılıyor')], default='Onay Bekliyor', max_length=50),
        ),
        migrations.AddField(
            model_name='tasimamodel',
            name='idari_calisan',
            field=models.CharField(choices=[('Pınar Hanım', 'Pınar Hanım'), ('Bahar Hanım', 'Bahar Hanım')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tasimamodel',
            name='islem_durumu',
            field=models.CharField(choices=[('Onay Bekliyor', 'Onay Bekliyor'), ('Onaylandı', 'Onaylandı'), ('Reddedildi', 'Reddedildi'), ('İşlem Yapılıyor', 'İşlem Yapılıyor')], default='Onay Bekliyor', max_length=50),
        ),
    ]
