# Generated by Django 4.1.8 on 2023-05-18 08:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_hijyenmodel_idari_calisan_hijyenmodel_islem_durumu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hijyenmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='baslik', unique=True),
        ),
    ]
