# Generated by Django 4.1.8 on 2023-05-18 08:30

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_hijyenmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarfmalzememodel',
            name='slug2',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, blank=True, editable=False, null=True, populate_from='baslik', unique=True),
        ),
        migrations.AddField(
            model_name='tasimamodel',
            name='slug1',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, blank=True, editable=False, null=True, populate_from='baslik', unique=True),
        ),
    ]
