# Generated by Django 4.1.8 on 2023-05-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_sarfmalzememodel_slug2_tasimamodel_slug1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sarfmalzememodel',
            old_name='slug2',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='tasimamodel',
            old_name='slug1',
            new_name='slug',
        ),
    ]
