# Generated by Django 4.1.8 on 2023-05-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_slug2_sarfmalzememodel_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasimamodel',
            name='idari_calisan',
            field=models.CharField(choices=[('Pınar Hanım', 'Pınar Hanım'), ('Bahar Hanım', 'Bahar Hanım')], default='Pınar Hanım', max_length=50, null=True),
        ),
    ]
