# Generated by Django 4.1.8 on 2023-05-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_tasimamodel_idari_calisan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sarfmalzememodel',
            name='kategori_ismi',
        ),
    ]
