# Generated by Django 4.1.8 on 2023-05-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_sarfmalzememodel_kategori_ismi'),
    ]

    operations = [
        migrations.AddField(
            model_name='hijyenmodel',
            name='kategori_adi',
            field=models.CharField(default='Hijyen', max_length=50, null=True),
        ),
    ]
