# Generated by Django 4.1.8 on 2023-05-19 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_hijyenmodel_form_gonderen'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarfmalzememodel',
            name='form_gonderen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sarf_formlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasimamodel',
            name='form_gonderen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasima_formlar', to=settings.AUTH_USER_MODEL),
        ),
    ]
