# Generated by Django 4.1.8 on 2023-05-20 11:00

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_sarfmalzememodel_form_gonderen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hijyenmodel',
            name='form_gonderen',
            field=models.ForeignKey(default=django.contrib.auth.models.AbstractUser.email_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijyen_formlar', to=settings.AUTH_USER_MODEL),
        ),
    ]
