# Generated by Django 4.1.8 on 2023-05-20 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_sarfmalzemeyanitmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HijyenYanitModel',
            fields=[
                ('gorevlimodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.gorevlimodel')),
                ('aciklama', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hijyen Yanıt Formu',
                'verbose_name_plural': 'Hijyen Yanıt Formları',
                'db_table': 'hijyen_yanit',
            },
            bases=('blog.gorevlimodel',),
        ),
    ]
