# Generated by Django 4.1.8 on 2023-05-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_tasimayanitmodel_remove_hijyenmodel_gorevli_kisi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hijyenyanitmodel',
            old_name='aciklama',
            new_name='hijyen_aciklama',
        ),
        migrations.AddField(
            model_name='hijyenyanitmodel',
            name='gorevli_sayi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gorevlimodel',
            name='gorevli_isim_soyisim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
