# Generated by Django 4.1.8 on 2023-05-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_rename_aciklama_hijyenyanitmodel_hijyen_aciklama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarfmalzememodel',
            name='sarf_aciklama',
            field=models.TextField(blank=True, null=True),
        ),
    ]
