# Generated by Django 4.1.8 on 2023-05-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_sarfmalzememodel_sarf_aciklama'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sarfmalzememodel',
            old_name='sarf_aciklama',
            new_name='sarf_yanit',
        ),
    ]
