# Generated by Django 4.1.8 on 2023-05-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_rename_sarf_aciklama_sarfmalzememodel_sarf_yanit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sarfmalzememodel',
            old_name='sarf_yanit',
            new_name='sarf_aciklama',
        ),
    ]
